logging:
  level:
    .: error
    org.springframework: ERROR
    eu.europa: ERROR

spring:
  application:
    name: FsWatcher
  profiles:
    active: "dev"
  main:
    banner-mode: "console"

server:
  email: support.aris@lutech.it

watcher:
  recursive: true
  folders: 
    - /tmp

---

spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    .: error
    org.springframework: DEBUG
    eu.europa: DEBUG
          
---

spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    .: error
    org.springframework: ERROR
    eu.europa: INFO
